### ISSUE TITLE
Cant figure out "first letter of classSection must be in 1-5" on the section field while creating class

### ISSUE THREAD

**Issue by Jalajj** [louayyahyaoui/Smart-Virtual-Classroom#5]
Can you explaing the issue mentioned in headline! By the way great project loved it...

**Comment by louayyahyaoui** [comment]
Hey there
about the validation of the section field the first letter should be 1-5 it is the classname for example 5DS1 means the 5th year of the class DS ( data science )

i hope the picture above explain the classSection

![GithubIssue](https://user-images.githubusercontent.com/49155930/170707025-5b68d7ee-b997-45fa-987f-a368287b0eeb.png)

**Comment by Jalajj** [comment]
> Hey there about the validation of the section field the first letter should be 1-5 it is the classname for example 5DS1 means the 5th year of the class DS ( data science )
> 
> i hope the picture above explain the classSection
> 
> ![GithubIssue](https://user-images.githubusercontent.com/49155930/170707025-5b68d7ee-b997-45fa-987f-a368287b0eeb.png)
Thank so much, there I got the issue now!
